Repository webb-tools/dkg-substrate, pull requests merged in 2022-02, with the labels that each got.

#144 rescue tokens evm proposal
  dkg-gadget/src/worker.rs
  dkg-runtime-primitives/src/proposal.rs
  pallets/dkg-proposal-handler/src/lib.rs
  pallets/dkg-proposal-handler/src/tests.rs
Labels: needs review

#149 Address issue #74 and its blockers
  dkg-gadget/src/worker.rs
  dkg-test-suite/src/testAnchorProposal.ts
  scripts/setup-exports.sh
Labels: needs review

#143 Fix persistence for key rotation
  dkg-gadget/src/persistence.rs
  dkg-gadget/src/utils.rs
  dkg-gadget/src/worker.rs
  dkg-primitives/src/rounds/dkg.rs
  dkg-primitives/src/rounds/keygen.rs
  dkg-primitives/src/rounds/offline.rs
  dkg-primitives/src/rounds/sign.rs
  dkg-primitives/src/types.rs
Labels: needs review

#155 Handle When DKG Signer Changes and the Signed Proposal is Signed by the old DKG.
  Cargo.lock
  dkg-runtime-primitives/Cargo.toml
  dkg-runtime-primitives/src/traits.rs
  dkg-runtime-primitives/src/utils.rs
  pallets/dkg-metadata/src/lib.rs
  pallets/dkg-metadata/src/mock.rs
  pallets/dkg-mmr/src/mock.rs
  pallets/dkg-proposal-handler/src/lib.rs
  pallets/dkg-proposal-handler/src/mock.rs
  pallets/dkg-proposal-handler/src/tests.rs
  pallets/dkg-proposals/src/mock.rs
  runtime/src/lib.rs
  standalone/runtime/src/lib.rs
Labels: needs review

#159 [TASK] Test token (add, remove, set fee) call proposals to the DKG for Substrate. according to #108
  dkg-test-suite/package.json
  dkg-test-suite/src/testAnchorProposal.ts
  dkg-test-suite/src/testVAnchorConfigurableLimitsProposal.ts
  dkg-test-suite/src/testWrappingFeeUpdateProposal.ts
  dkg-test-suite/src/token/testTokenAddProposal.ts
  dkg-test-suite/src/token/testTokenRemoveProposal.ts
  dkg-test-suite/src/util/proposals.ts
  dkg-test-suite/src/util/resource.ts
  dkg-test-suite/src/utils.ts
  dkg-test-suite/src/v-anchor-configurable-limit/testMaxDepositLimitUpdateProposal.ts
  dkg-test-suite/src/v-anchor-configurable-limit/testMaxExtLimitUpdate.ts
  dkg-test-suite/src/v-anchor-configurable-limit/testMaxFeeLimitUpdateProposal.ts
  dkg-test-suite/src/v-anchor-configurable-limit/testMinWithdrawalLimitUpdateProposal.ts
Labels: needs review

#158 chore - add issue template and pull request templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/checklist_issue.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/new_issue.md
  .github/ISSUE_TEMPLATE/spec_issue.md
  .github/ISSUE_TEMPLATE/task_issue.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: needs review

#162 match chain type when decoding prop
  dkg-gadget/src/worker.rs
  dkg-primitives/src/rounds/sign.rs
  dkg-runtime-primitives/src/handlers/decode_proposals.rs
  dkg-runtime-primitives/src/handlers/evm/add_token_to_set.rs
  dkg-runtime-primitives/src/handlers/evm/anchor_update.rs
  dkg-runtime-primitives/src/handlers/evm/bytes32_update.rs
  dkg-runtime-primitives/src/handlers/evm/evm_tx.rs
  dkg-runtime-primitives/src/handlers/evm/fee_update.rs
  dkg-runtime-primitives/src/handlers/evm/mod.rs
  dkg-runtime-primitives/src/handlers/evm/remove_token_from_set.rs
  dkg-runtime-primitives/src/handlers/evm/rescue_tokens.rs
  dkg-runtime-primitives/src/handlers/evm/resource_id_update.rs
  dkg-runtime-primitives/src/handlers/mod.rs
  dkg-runtime-primitives/src/handlers/substrate/mod.rs
  dkg-runtime-primitives/src/handlers/validate_proposals.rs
  dkg-runtime-primitives/src/lib.rs
  dkg-runtime-primitives/src/proposal.rs
  dkg-runtime-primitives/src/utils.rs
  pallets/dkg-metadata/src/lib.rs
  pallets/dkg-proposal-handler/src/lib.rs
  pallets/dkg-proposal-handler/src/tests.rs
  pallets/dkg-proposals/src/tests.rs
Labels: approved

#153 Add code coverage to testing and CI
  .github/workflows/coverage.yml
  README.md
  docker/Coverage.Dockerfile
Labels: needs review

#165 chore: optimize test ci using nextest
  .github/workflows/test-code.yml
Labels: needs review

#163 Improve docs for dkg-primitives
  dkg-primitives/src/rounds/dkg.rs
  dkg-primitives/src/rounds/keygen.rs
  dkg-primitives/src/rounds/offline.rs
  dkg-primitives/src/rounds/sign.rs
Labels: approved

#164 Fixing signing bugs, add misbehaviour reported
  dkg-gadget/src/persistence.rs
  dkg-gadget/src/utils.rs
  dkg-gadget/src/worker.rs
  dkg-primitives/src/rounds/dkg.rs
  dkg-primitives/src/rounds/sign.rs
  dkg-primitives/src/types.rs
  dkg-runtime-primitives/src/lib.rs
  dkg-runtime-primitives/src/offchain/crypto.rs
  dkg-runtime-primitives/src/offchain/mod.rs
  dkg-runtime-primitives/src/offchain/storage_keys.rs
  pallets/dkg-metadata/src/lib.rs
  pallets/dkg-metadata/src/mock.rs
  pallets/dkg-mmr/src/mock.rs
  pallets/dkg-proposal-handler/src/lib.rs
  pallets/dkg-proposal-handler/src/mock.rs
  pallets/dkg-proposal-handler/src/tests.rs
  pallets/dkg-proposals/src/mock.rs
  runtime/src/lib.rs
  standalone/runtime/src/lib.rs
Labels: needs review

#178 chore: add codecov config, bump nexttest version
  .github/workflows/coverage.yml
  .github/workflows/test-code.yml
  codecov.yml
Labels: needs review

#175 add remaining evm proposals to dkg
  dkg-gadget/src/worker.rs
  dkg-runtime-primitives/src/handlers/decode_proposals.rs
  dkg-runtime-primitives/src/handlers/evm/fee_recipient_update.rs
  dkg-runtime-primitives/src/handlers/evm/mod.rs
  dkg-runtime-primitives/src/handlers/evm/set_treasury_handler.rs
  dkg-runtime-primitives/src/handlers/evm/set_verifier.rs
  dkg-runtime-primitives/src/proposal.rs
  dkg-test-suite/package.json
  dkg-test-suite/src/evm/testFeeRecipientUpdateProposal.ts
  dkg-test-suite/src/evm/testSetTreasuryHandlerProposal.ts
  dkg-test-suite/src/evm/testSetVerifierProposal.ts
  dkg-test-suite/src/evm/util/proposals.ts
  dkg-test-suite/src/evm/util/utils.ts
  pallets/dkg-proposal-handler/src/tests.rs
Labels: needs review

#179 [TEST] Add End To End Testing For Anchor Update Proposal over Signature Bridge and the DKG
  dkg-runtime-primitives/src/handlers/evm/anchor_update.rs
  dkg-test-suite/package.json
  dkg-test-suite/src/constants.ts
  dkg-test-suite/src/localEvm.ts
  dkg-test-suite/src/substrate/util/utils.ts
  dkg-test-suite/src/utils.ts
  dkg-test-suite/tests/updateAnchorProposal.test.ts
  dkg-test-suite/tests/updateGovernor.test.ts
  scripts/run-standalone.sh
Labels: type: testing, needs review

#177 implement storage lock for offchain workers
  dkg-runtime-primitives/src/offchain/storage_keys.rs
  pallets/dkg-metadata/src/lib.rs
  pallets/dkg-proposal-handler/src/lib.rs
Labels: needs review

#184 resource id proposal unit and integration (non e2e) tests
  dkg-runtime-primitives/src/handlers/decode_proposals.rs
  dkg-runtime-primitives/src/handlers/substrate/mod.rs
  dkg-runtime-primitives/src/handlers/substrate/resource_id_update.rs
  dkg-test-suite/package.json
  dkg-test-suite/src/evm/testResourceIdUpdateProposal.ts
  dkg-test-suite/src/evm/util/proposals.ts
  dkg-test-suite/src/evm/util/utils.ts
  dkg-test-suite/src/substrate/testResourceIdUpdateProposal.ts
  dkg-test-suite/src/substrate/util/proposals.ts
  dkg-test-suite/src/substrate/util/utils.ts
  dkg-test-suite/src/utils.ts
  dkg-test-suite/tests/updateAnchorProposal.test.ts
  dkg-test-suite/tests/updateGovernor.test.ts
  dkg-test-suite/tsconfig.json
  pallets/dkg-proposal-handler/src/tests.rs
Labels: needs review
