Repository webb-tools/dkg-substrate, pull requests merged in 2022-06, with the labels that each got.

#313 chore: updates ci to match every branch
  .github/workflows/checks.yml
  .github/workflows/e2e.yml
  .github/workflows/tests.yml
  README.md
Labels: needs review 👓

#327 Multi set signing async
  dkg-gadget/src/async_protocols/sign/handler.rs
  dkg-gadget/src/worker.rs
Labels: needs changes 🔧

#332 Fix Keygen Threshold updates
  dkg-gadget/src/worker.rs
  dkg-runtime-primitives/src/utils.rs
  pallets/dkg-metadata/src/lib.rs
  pallets/dkg-proposal-handler/src/lib.rs
Labels: optimization ⚙️, testing 🛠️, needs review 👓
