Repository webb-tools/dkg-substrate, pull requests merged in 2022-03, with the labels that each got.

#195 started rescue token proposal test
  dkg-test-suite/package.json
  dkg-test-suite/src/utils.ts
  dkg-test-suite/tests/rescueTokensProposal.test.ts
  dkg-test-suite/tests/wrappingFeeUpdateProposal.test.ts
  dkg-test-suite/yarn.lock
Labels: approved

#218 chore: adds rust docs publication on push to master
  .github/workflows/publish-rust-docs.yml
  scripts/build-rust-docs.sh
Labels: needs review

#198 Parachain updates
  .github/workflows/coverage.yml
  .gitignore
  Cargo.lock
  README.md
  dkg-gadget/src/gossip.rs
  dkg-gadget/src/worker.rs
  dkg-primitives/src/rounds/dkg.rs
  dkg-primitives/src/rounds/keygen.rs
  docker/Coverage.Dockerfile
  docker/Parachain.Dockerfile
  launch/.gitignore
  launch/config.yml
  launch/package.json
  launch/yarn.lock
  node/Cargo.toml
  node/src/chain_spec.rs
  node/src/cli.rs
  node/src/command.rs
  node/src/service.rs
  pallets/dkg-metadata/Cargo.toml
  pallets/dkg-proposal-handler/Cargo.toml
  pallets/dkg-proposals/Cargo.toml
  pallets/dkg-proposals/src/mock.rs
  pallets/dkg-proposals/src/tests.rs
  pallets/parachain-staking/Cargo.toml
  pallets/parachain-staking/src/benchmarks.rs
  pallets/parachain-staking/src/inflation.rs
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/mock.rs
  pallets/parachain-staking/src/set.rs
  pallets/parachain-staking/src/tests.rs
  pallets/parachain-staking/src/weights.rs
  resources/template-local-plain.json
  resources/template-local-raw.json
  runtime/Cargo.toml
  runtime/src/lib.rs
  scripts/docker-hub-publish-dkg-node.sh
  scripts/polkadot-launch/dkg-launch.json
  scripts/polkadot-launch/rococo-local-raw.json
  scripts/polkadot-launch/rococo-local.json
  standalone/node/src/service.rs
Labels: needs review

#221 chore: update readme to include macos dependency for gmp
  README.md
Labels: needs review

#219 Dami/cleanups
  dkg-gadget/src/keyring.rs
  dkg-gadget/src/lib.rs
  dkg-gadget/src/messages/dkg_message.rs
  dkg-gadget/src/messages/mod.rs
  dkg-gadget/src/persistence.rs
  dkg-gadget/src/proposal.rs
  dkg-gadget/src/utils.rs
  dkg-gadget/src/worker.rs
  dkg-primitives/src/rounds/dkg.rs
  dkg-runtime-primitives/src/handlers/evm/add_token_to_set.rs
  dkg-runtime-primitives/src/handlers/evm/anchor_update.rs
  dkg-runtime-primitives/src/handlers/evm/bytes32_update.rs
  dkg-runtime-primitives/src/handlers/evm/evm_tx.rs
  dkg-runtime-primitives/src/handlers/evm/fee_recipient_update.rs
  dkg-runtime-primitives/src/handlers/evm/fee_update.rs
  dkg-runtime-primitives/src/handlers/evm/remove_token_from_set.rs
  dkg-runtime-primitives/src/handlers/evm/rescue_tokens.rs
  dkg-runtime-primitives/src/handlers/evm/resource_id_update.rs
  dkg-runtime-primitives/src/handlers/evm/set_treasury_handler.rs
  dkg-runtime-primitives/src/handlers/evm/set_verifier.rs
  dkg-runtime-primitives/src/handlers/substrate/add_token_to_pool_share.rs
  dkg-runtime-primitives/src/handlers/substrate/anchor_create.rs
  dkg-runtime-primitives/src/handlers/substrate/anchor_update.rs
  dkg-runtime-primitives/src/handlers/substrate/fee_update.rs
  dkg-runtime-primitives/src/handlers/substrate/remove_token_from_pool_share.rs
  dkg-runtime-primitives/src/handlers/substrate/resource_id_update.rs
  dkg-runtime-primitives/src/lib.rs
  dkg-runtime-primitives/src/proposal.rs
  pallets/dkg-metadata/src/lib.rs
Labels: needs review

#224 Ensure function sig is not zero in anchor_update.rs
  dkg-runtime-primitives/src/handlers/evm/anchor_update.rs
Labels: needs review

#225 Dami/remove test warnings
  dkg-gadget/src/gossip.rs
  dkg-gadget/src/lib.rs
  dkg-gadget/src/messages/dkg_message.rs
  dkg-gadget/src/messages/misbehaviour_report.rs
  dkg-gadget/src/messages/public_key_gossip.rs
  dkg-gadget/src/metrics.rs
  dkg-gadget/src/persistence.rs
  dkg-gadget/src/proposal.rs
  dkg-gadget/src/utils.rs
  dkg-gadget/src/worker.rs
  dkg-primitives/src/rounds/dkg.rs
  dkg-primitives/src/rounds/keygen.rs
  dkg-primitives/src/rounds/offline.rs
  dkg-primitives/src/rounds/sign.rs
  dkg-runtime-primitives/src/handlers/evm/bytes32_update.rs
  dkg-runtime-primitives/src/handlers/substrate/resource_id_update.rs
  dkg-runtime-primitives/src/lib.rs
  node/src/chain_spec.rs
  node/src/service.rs
  pallets/dkg-metadata/src/mock.rs
  pallets/dkg-metadata/src/tests.rs
  pallets/dkg-proposal-handler/src/lib.rs
  pallets/dkg-proposal-handler/src/mock.rs
  pallets/dkg-proposal-handler/src/tests.rs
  pallets/dkg-proposals/src/mock.rs
  runtime/src/lib.rs
  standalone/node/src/chain_spec.rs
  standalone/node/src/service.rs
  standalone/runtime/src/lib.rs
Labels: needs changes

#236 chore: adds rococo-native feature
  node/Cargo.toml
Labels: needs review

#193 proposer set update
  .github/workflows/coverage.yml
  Cargo.lock
  dkg-gadget/src/proposal.rs
  dkg-runtime-primitives/src/handlers/decode_proposals.rs
  dkg-runtime-primitives/src/handlers/mod.rs
  dkg-runtime-primitives/src/handlers/proposer_set_update.rs
  dkg-runtime-primitives/src/lib.rs
  dkg-runtime-primitives/src/mmr.rs
  dkg-runtime-primitives/src/proposal.rs
  dkg-runtime-primitives/src/traits.rs
  pallets/dkg-metadata/src/lib.rs
  pallets/dkg-proposal-handler/Cargo.toml
  pallets/dkg-proposal-handler/src/lib.rs
  pallets/dkg-proposal-handler/src/mock.rs
  pallets/dkg-proposal-handler/src/tests.rs
  pallets/dkg-proposals/Cargo.toml
  pallets/dkg-proposals/src/lib.rs
  pallets/dkg-proposals/src/mock.rs
  pallets/dkg-proposals/src/tests.rs
  runtime/src/lib.rs
  standalone/runtime/src/lib.rs
Labels: needs review

#255 chore: update readme to include test instructions
  README.md
Labels: needs review

#250 updated benchmarks
  node/Cargo.toml
  pallets/dkg-proposal-handler/Cargo.toml
  pallets/dkg-proposal-handler/src/benchmarking.rs
  pallets/dkg-proposal-handler/src/weights.rs
  pallets/dkg-proposals/src/benchmarking.rs
  pallets/dkg-proposals/src/weights.rs
Labels: needs review

#263 Remove warnings and benchmark updates
  .github/workflows/warnings.yml
  Cargo.lock
  dkg-gadget/src/error.rs
  dkg-gadget/src/keystore.rs
  dkg-gadget/src/messages/dkg_message.rs
  dkg-gadget/src/messages/misbehaviour_report.rs
  dkg-gadget/src/messages/public_key_gossip.rs
  dkg-gadget/src/persistence.rs
  dkg-gadget/src/proposal.rs
  dkg-gadget/src/storage/proposals.rs
  dkg-gadget/src/storage/public_keys.rs
  dkg-gadget/src/utils.rs
  dkg-gadget/src/worker.rs
  dkg-primitives/src/keys.rs
  dkg-primitives/src/rounds/dkg.rs
  dkg-primitives/src/rounds/keygen.rs
  dkg-primitives/src/rounds/offline.rs
  dkg-primitives/src/rounds/sign.rs
  dkg-primitives/src/types.rs
  dkg-primitives/src/utils.rs
  dkg-runtime-primitives/src/handlers/evm/bytes32_update.rs
  dkg-runtime-primitives/src/handlers/evm/evm_tx.rs
  dkg-runtime-primitives/src/handlers/proposer_set_update.rs
  dkg-runtime-primitives/src/handlers/substrate/add_token_to_pool_share.rs
  dkg-runtime-primitives/src/handlers/substrate/anchor_create.rs
  dkg-runtime-primitives/src/handlers/substrate/anchor_update.rs
  dkg-runtime-primitives/src/handlers/substrate/fee_update.rs
  dkg-runtime-primitives/src/handlers/substrate/remove_token_from_pool_share.rs
  dkg-runtime-primitives/src/proposal.rs
  dkg-runtime-primitives/src/traits.rs
  dkg-runtime-primitives/src/utils.rs
  node/Cargo.toml
  node/src/chain_spec.rs
  node/src/cli.rs
  node/src/command.rs
  node/src/service.rs
  pallets/dkg-metadata/src/lib.rs
  pallets/dkg-metadata/src/mock.rs
  pallets/dkg-proposal-handler/src/benchmarking.rs
  pallets/dkg-proposal-handler/src/lib.rs
  pallets/dkg-proposal-handler/src/mock.rs
  pallets/dkg-proposal-handler/src/tests.rs
  pallets/dkg-proposal-handler/src/weights.rs
  pallets/dkg-proposals/Cargo.toml
  pallets/dkg-proposals/src/benchmarking.rs
  pallets/dkg-proposals/src/lib.rs
  pallets/dkg-proposals/src/mock.rs
  pallets/dkg-proposals/src/tests.rs
  pallets/dkg-proposals/src/types.rs
  pallets/dkg-proposals/src/weights.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
  standalone/node/src/chain_spec.rs
  standalone/node/src/command.rs
  standalone/node/src/rpc.rs
  standalone/node/src/service.rs
  standalone/node/src/testnet_fixtures.rs
  standalone/runtime/Cargo.toml
  standalone/runtime/src/lib.rs
Labels: wip

#271 chore: refactor github actions to improve speed and consolidate workflow files
  .github/workflows/checks.yml
  .github/workflows/coverage.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/image-publish.yml
  .github/workflows/publish-rust-docs.yml
  .github/workflows/test-code.yml
  .github/workflows/tests.yml
  .github/workflows/warnings.yml
Labels: needs review
