Repository webb-tools/dkg-substrate, pull requests merged in 2022-10, with the labels that each got.

#415 chore: split ci jobs into two
  .github/workflows/e2e.yml
  dkg-gadget/src/gossip_engine/network.rs
  pallets/bridge-registry/src/weights.rs
  pallets/dkg-metadata/src/lib.rs
  pallets/dkg-metadata/src/weights.rs
Labels: needs review 👓

#423 chore: updates chainspec
  chainspecs/stable-arana-specs-raw.json
Labels: needs review 👓

#427 [TASK] Remove running next DKG on genesis and use the proper mechanism once the session has elapsed
  dkg-gadget/src/worker.rs
Labels: needs review 👓

#426 [TASK] Track session rotation period from the start of the last session
  pallets/dkg-metadata/src/lib.rs
Labels: needs review 👓

#436 Reorganise the logic for the offchain storage in the DKG pallet
  pallets/dkg-metadata/Cargo.toml
  pallets/dkg-metadata/src/lib.rs
Labels: p1 🟠, optimization ⚙️, needs review 👓

#437 Change Offchain worker txs to be free
  pallets/dkg-metadata/src/lib.rs
  pallets/dkg-metadata/src/mock.rs
  pallets/dkg-proposal-handler/src/lib.rs
  pallets/dkg-proposal-handler/src/mock.rs
  pallets/dkg-proposals/src/mock.rs
  parachain/runtime/rococo/src/lib.rs
  standalone/runtime/src/lib.rs
Labels: optimization ⚙️, needs review 👓
